apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: scaletestapp
  namespaceSelector:
    matchNames:
      - insure-tech
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s